require "pry"

def game_hash
  hasketball = {
    :home => {
      :team_name => "",
      :colors => [],
      :players => [
        {{:player_name => "Alan Anderson"},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        {{:player_name => "Reggie Evans"},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        {{:player_name => "Brook Lopez"},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        {{:player_name => "Mason Plumlee"},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        {{:player_name => "Mason Plumlee"},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        ]
    },
    :away => {
      :team_name => "",
      :colors => [],
      ::players => [
        {{:player_name => ""},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        {{:player_name => ""},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        {{:player_name => ""},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}},
        {{:player_name => ""},
        {:number =>},
        {:shoe =>},
        {:points =>},
        {:rebounds => },
        {:assists =>},
        {:steals =>},
        {:blocks =>},
        {:slam_dunks =>}}
        ]
    }
  }

end